### ISSUE TITLE
API Chaining is trademarked

### ISSUE THREAD

**Issue by orubel** [mikestowe/REST-API-Multiple-Request-Chaining#1]
I don't mind you talking and I think your implementation is DEFINITELY the best I have seen so far but PLEASE don't call it an idea. It's a fully implemented and working concept and has been since 2013 in a project... hence why I trademarked the term. I had put the functionality into an open source project and that allowed me to say who could apply the term (much as Linux uses their trademark).

If you would like to see documentation the link is here (https://github.com/orubel/grails-api-toolkit-docs/wiki/API-Chaining)

**Comment by mikestowe** [comment]
Per your request, and out of respect, I have revised the title of this repository.  I've also added clarification on how this method differs from the proposed concept of API Chaining within an IO State driven API, and added a link to your specification in the FAQs.
